name: UnrealChest
version: '${version}'
main: com.daxton.unrealchest.UnrealChest
api-version: '1.16'
softdepend: [UnrealCore]

folia-supported: true

commands:
  unrealchest:
    description: Basic instructions.
    aliases: uchest